Se adjuntan evidencias. Durante el ejercicio debí desinstalar danjgo 4.0 y volver a 3.2 ya que rest-auth no es compatible con django 4.0 (en este último se ha eliminado el objerto url)
![image](https://user-images.githubusercontent.com/77200841/162626253-2dc56ec5-2b36-43b4-b561-ffde36f0c84c.png)
![image](https://user-images.githubusercontent.com/77200841/162626280-73e8c599-b209-4cfd-a145-20bf3e65ea91.png)
![image](https://user-images.githubusercontent.com/77200841/162626300-ab21ea74-34a7-43c4-ad76-a4d850c11336.png)
![image](https://user-images.githubusercontent.com/77200841/162626309-dbbbd77c-f0d5-47cd-a23f-e359469efa68.png)
![image](https://user-images.githubusercontent.com/77200841/162626315-416fd41d-59d8-4532-8050-e74183a2b0aa.png)
![image](https://user-images.githubusercontent.com/77200841/162626319-f35cc9db-b9c8-465b-ae95-541dec730fd1.png)

  
  
  
