Se adjuntan evidencias. Durante el ejercicio debí desinstalar danjgo 4.0 y volver a 3.2 ya que rest-auth no es compatible con django 4.0 (en este último se ha eliminado el objerto url)

  
  
